site_name: FastAPI HyperModel
theme:
  name: material
  features:
    - content.code.copy

repo_name: jtc42/fastapi-hypermodel
repo_url: https://github.com/jtc42/fastapi-hypermodel

extra_javascript:
  - js/linked_tabs.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

docs_dir: './docs'

nav:
  - Home: 'index.md'
  - Basic Usage: 'basics.md'
  - Use Cases: 'use_cases.md'
  - Advanced Usage: 'advanced.md'
  - Extending FastAPI-HyperModel: 'extending.md'
